# EngineRuntimeConfig.cmake — package config for the installed engine SDK.
#
#   find_package(EngineRuntime REQUIRED)
#   target_link_libraries(my_game PRIVATE engine::runtime)
#
# Hand-written (not generated by install(EXPORT)) because the SDK bundles
# several vendored third-party static libraries whose targets don't define
# install interfaces. Everything is resolved relative to this file, so the
# install tree is relocatable.

if(TARGET engine::runtime)
    return()
endif()

include(CMakeFindDependencyMacro)
find_dependency(SQLite3)            # assetlib uses the system sqlite3

get_filename_component(_engine_prefix "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

# Static libraries bundled in <prefix>/lib. Debug builds carry a 'd' postfix
# (inherited from the vendored projects), so accept both names.
set(_engine_libs
    engine_runtime
    assetlib
    assimp
    bgfx bimg bx
    glfw3
    flecs_static
    Jolt
    lua
)
set(_engine_resolved "")
foreach(_lib IN LISTS _engine_libs)
    find_library(ENGINE_LIB_${_lib}
        NAMES ${_lib} ${_lib}d
        PATHS "${_engine_prefix}/lib"
        NO_DEFAULT_PATH)
    if(NOT ENGINE_LIB_${_lib})
        set(EngineRuntime_FOUND FALSE)
        set(EngineRuntime_NOT_FOUND_MESSAGE
            "missing bundled library '${_lib}' in ${_engine_prefix}/lib")
        return()
    endif()
    list(APPEND _engine_resolved "${ENGINE_LIB_${_lib}}")
endforeach()

# The definitions the bundled libraries were built with — ABI-critical for
# Jolt and bx. Generated at SDK build time alongside this file.
include("${CMAKE_CURRENT_LIST_DIR}/EngineRuntimeDefinitions.cmake")
list(REMOVE_DUPLICATES ENGINE_BUNDLED_DEFINITIONS)
list(FILTER ENGINE_BUNDLED_DEFINITIONS EXCLUDE REGEX "^$")

add_library(engine::runtime INTERFACE IMPORTED)
set_target_properties(engine::runtime PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_engine_prefix}/include"
    INTERFACE_COMPILE_DEFINITIONS
        "BGFX_PLATFORM_SUPPORTS_WGSL=0;${ENGINE_BUNDLED_DEFINITIONS}"
)
target_compile_features(engine::runtime INTERFACE cxx_std_20)
target_link_libraries(engine::runtime INTERFACE
    ${_engine_resolved}
    SQLite::SQLite3
)

if(APPLE)
    target_link_libraries(engine::runtime INTERFACE
        "-framework Cocoa"
        "-framework QuartzCore"
        "-framework Metal"
        "-framework IOKit"
        "-framework CoreAudio"
        "-framework AudioToolbox"
        "-framework AudioUnit"
        "-framework CoreFoundation"
        "-framework CoreServices"   # assetlib file watcher
        z                           # assimp uses system zlib
    )
elseif(WIN32)
    target_link_libraries(engine::runtime INTERFACE
        gdi32 shell32 user32 winmm
    )
else()
    find_dependency(Threads)
    find_package(X11 REQUIRED)
    target_link_libraries(engine::runtime INTERFACE
        ${X11_LIBRARIES} Threads::Threads dl z
    )
endif()

set(EngineRuntime_FOUND TRUE)
